In [4]:
from sqlalchemy import create_engine
from sqlalchemy import text
from sqlalchemy import inspect
import pandas as pd

In [3]:
engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/postgres")

In [5]:
inspector = inspect(engine)
tables = inspector.get_table_names(schema="public")

In [6]:
tables

['historical_aqi_table',
 'historical_weather_aqi_table',
 'risk_prediction_indian_cities_coordinates',
 'historical_weather_table',
 'weather_aqi_train',
 'weather_aqi_val',
 'weather_aqi_test',
 'weather_aqi_processed_train',
 'weather_aqi_processed_val',
 'weather_aqi_processed_test']

In [3]:
import yaml
file_path = "/Users/amritamandal/Desktop/Python/MLOPS/Short-term-PM2.5-prediction-model-MLOPS/config/parameters.yaml"
def read_yaml_file(file_path: str) -> dict:
    with open(file_path, "r") as f:
        return yaml.safe_load(f)

In [4]:
yaml_file = read_yaml_file(file_path)

In [8]:
yaml_file['models']['XGBoost']['params']

{'n_estimators': [300, 500],
 'max_depth': [6, 8],
 'learning_rate': [0.01, 0.05],
 'subsample': [0.8, 1.0]}

In [10]:
for module in yaml_file['models']:
    print

{'RandomForest': {'class': 'RandomForestRegressor',
  'module': 'sklearn.ensemble',
  'params': {'n_estimators': [500, 1000, 1500],
   'max_depth': [10, 15, 20],
   'learning_rate': [0.01, 0.05],
   'min_samples_split': [2, 5],
   'min_samples_leaf': [1, 2]}},
 'XGBoost': {'class': 'XGBRegressor',
  'module': 'xgboost',
  'params': {'n_estimators': [300, 500],
   'max_depth': [6, 8],
   'learning_rate': [0.01, 0.05],
   'subsample': [0.8, 1.0]}},
 'LightGBM': {'class': 'LGBMRegressor',
  'module': 'lightgbm',
  'params': {'n_estimators': [300, 500, 1000],
   'num_leaves': [31, 63],
   'learning_rate': [0.01, 0.02, 0.05]}},
 'GradientBoosting': {'class': 'GradientBoostingRegressor',
  'module': 'sklearn.ensemble',
  'params': {'n_estimators': [200, 300, 500], 'learning_rate': [0.01, 0.05]}}}

In [12]:
for model_type, model_cfg in yaml_file['models'].items():
    print(model_type)
    print(model_cfg["class"])
    print(model_cfg["module"])
    print(model_cfg["params"])

RandomForest
RandomForestRegressor
sklearn.ensemble
{'n_estimators': [500, 1000, 1500], 'max_depth': [10, 15, 20], 'learning_rate': [0.01, 0.05], 'min_samples_split': [2, 5], 'min_samples_leaf': [1, 2]}
XGBoost
XGBRegressor
xgboost
{'n_estimators': [300, 500], 'max_depth': [6, 8], 'learning_rate': [0.01, 0.05], 'subsample': [0.8, 1.0]}
LightGBM
LGBMRegressor
lightgbm
{'n_estimators': [300, 500, 1000], 'num_leaves': [31, 63], 'learning_rate': [0.01, 0.02, 0.05]}
GradientBoosting
GradientBoostingRegressor
sklearn.ensemble
{'n_estimators': [200, 300, 500], 'learning_rate': [0.01, 0.05]}

In [4]:
import numpy as np
with open("/Users/amritamandal/Desktop/Python/MLOPS/Short-term-PM2.5-prediction-model-MLOPS/artifact/01_12_2026_23_32_54/data_transformation/transformed/train.npy", 'rb') as file_obj:
    data = np.load(file_obj,allow_pickle=True)

In [8]:
import json
best_params = {
    'best_model_type':'Gradient Boosting',
    'judgement_criteria':'Adjusted R2',
    'learning_rate':0.05,
    'max_depth':5,
    'n_estimators':300,
    'random_state':42
}
with open("/Users/amritamandal/Desktop/Python/MLOPS/Short-term-PM2.5-prediction-model-MLOPS/artifact/01_13_2026_12_55_36/model_trainer/trained_model/best_model_params.json",'w') as f:
    json.dump(best_params,f)

In [10]:
best_metrics= {
    'adj_R2':0.83,
    'R2':0.83,
    'MAE':10.58,
    'RMSE':5.75,
}
with open("/Users/amritamandal/Desktop/Python/MLOPS/Short-term-PM2.5-prediction-model-MLOPS/artifact/01_13_2026_12_55_36/model_trainer/trained_model/best_model_metrics.json",'w') as f:
    json.dump(best_metrics,f)

In [6]:
import requests
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
            "latitude":27.59497,
            "longitude":93.83854,
            "start_date":"2026-01-01",
            'end_date':"2026-01-02",
            'daily':['temperature_2m_max','temperature_2m_min','apparent_temperature_max','apparent_temperature_min','precipitation_sum','rain_sum','snowfall_sum','precipitation_hours','sunshine_duration','daylight_duration','wind_speed_10m_max','wind_gusts_10m_max','shortwave_radiation_sum','et0_fao_evapotranspiration'],
            'timezone':'auto'
        }

response = requests.get(url = url, params = params).json()

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [5]:
response

{'latitude': 16.48506,
 'longitude': 80.65714,
 'generationtime_ms': 51.24223232269287,
 'utc_offset_seconds': 19800,
 'timezone': 'Asia/Kolkata',
 'timezone_abbreviation': 'GMT+5:30',
 'elevation': 28.0,
 'daily_units': {'time': 'iso8601',
  'temperature_2m_max': '°C',
  'temperature_2m_min': '°C',
  'apparent_temperature_max': '°C',
  'apparent_temperature_min': '°C',
  'precipitation_sum': 'mm',
  'rain_sum': 'mm',
  'snowfall_sum': 'cm',
  'precipitation_hours': 'h',
  'sunshine_duration': 's',
  'daylight_duration': 's',
  'wind_speed_10m_max': 'km/h',
  'wind_gusts_10m_max': 'km/h',
  'shortwave_radiation_sum': 'MJ/m²',
  'et0_fao_evapotranspiration': 'mm'},
 'daily': {'time': ['2026-01-01', '2026-01-02'],
  'temperature_2m_max': [31.0, 30.9],
  'temperature_2m_min': [20.8, 20.6],
  'apparent_temperature_max': [33.0, 32.5],
  'apparent_temperature_min': [23.8, 23.4],
  'precipitation_sum': [0.2, 0.0],
  'rain_sum': [0.2, 0.0],
  'snowfall_sum': [0.0, 0.0],
  'precipitation_hours': [2.0, 0.0],
  'sunshine_duration': [36671.17, 37058.62],
  'daylight_duration': [40193.65, 40207.52],
  'wind_speed_10m_max': [12.5, 12.5],
  'wind_gusts_10m_max': [27.4, 24.1],
  'shortwave_radiation_sum': [16.81, 17.14],
  'et0_fao_evapotranspiration': [3.77, 3.85]}}

In [9]:
import pandas as pd
df = pd.read_csv("/Users/amritamandal/Desktop/Python/MLOPS/Short-term-PM2.5-prediction-model-MLOPS/data_extraction_api/coordinates.csv",sep = ',')

In [12]:
df.iloc[2]['latitude']

np.float64(16.29974)

In [13]:
import psycopg2
import pandas as pd
conn = None
conn = psycopg2.connect(
host="localhost",
database="postgres",
user="postgres",
password="1234",
port=5432
)
cursor = conn.cursor()

In [37]:
cursor.execute("DROP TABLE historical_weather_table_predictions;")
conn.commit()

In [15]:
from sqlalchemy import create_engine
import pandas as pd
engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/postgres")

In [39]:
df_fetch = pd.read_sql_table("historical_weather_table_predictions", con=engine)

In [25]:
df_fetch.groupby(['id','state','place','time']).size().reset_index()['state'].unique()

array(['Kerala', 'Jammu and Kashmir',
       'Dadra and Nagar Haveli and Daman and Diu', 'Assam', 'Meghalaya',
       'Uttarakhand', 'Odisha', 'Chhattisgarh',
       'Andaman and Nicobar Islands', 'Puducherry', 'Bihar', 'Delhi',
       'Tamil Nadu', 'Uttar Pradesh', 'Rajasthan', 'Jharkhand',
       'Madhya Pradesh', 'Arunachal Pradesh', 'Manipur', 'Telangana',
       'Haryana', 'Nagaland', 'Himachal Pradesh', 'Goa', 'Chandigarh',
       'West Bengal', 'Maharashtra', 'Karnataka', 'Punjab', 'Mizoram',
       'Tripura', 'Ladakh', 'Sikkim', 'Lakshadweep'], dtype=object)

In [26]:
df_fetch

,id,state,place,latitude,longitude,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,...,rain_sum,snowfall_sum,precipitation_hours,sunshine_duration,daylight_duration,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,et0_fao_evapotranspiration,time
0,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,None,19.6,8.4,19.1,6.7,...,0.0,0.0,0.0,34746.61,37809.66,6.8,21.2,12.52,2.06,2026-01-05
1,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,None,19.5,8.1,18.6,6.7,...,0.0,0.0,0.0,34845.00,37843.70,8.2,23.4,12.91,2.11,2026-01-06
2,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,None,19.5,7.6,18.6,5.8,...,0.0,0.0,0.0,34884.99,37879.98,7.1,22.3,13.05,2.15,2026-01-07
3,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,None,20.7,8.2,19.6,6.6,...,0.0,0.0,0.0,34927.34,37918.44,6.9,21.2,13.09,2.23,2026-01-08
4,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,None,21.7,7.9,20.9,6.0,...,0.0,0.0,0.0,34971.93,37958.98,7.7,21.6,13.04,2.31,2026-01-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8920,1259425,Puducherry,Puducherry,11.93381,79.82979,None,27.0,22.0,32.4,25.5,...,0.1,0.0,1.0,35049.68,41398.20,13.9,28.1,18.88,3.67,2026-01-15
8921,1259425,Puducherry,Puducherry,11.93381,79.82979,None,27.0,22.2,30.7,25.3,...,0.2,0.0,2.0,37780.40,41419.55,16.1,31.0,20.08,4.11,2026-01-16
8922,1259425,Puducherry,Puducherry,11.93381,79.82979,None,26.6,21.0,30.0,23.1,...,1.8,0.0,3.0,37313.97,41441.52,19.4,42.1,19.47,4.18,2026-01-17
8923,1259425,Puducherry,Puducherry,11.93381,79.82979,None,27.0,19.7,29.9,21.3,...,0.0,0.0,0.0,38093.04,41464.07,11.5,29.9,20.95,4.32,2026-01-18
8924,1259425,Puducherry,Puducherry,11.93381,79.82979,None,27.6,19.8,30.7,21.5,...,0.0,0.0,0.0,36353.65,41487.17,14.0,34.6,20.37,4.38,2026-01-19

In [28]:
df_fetch = df_fetch.drop_duplicates()

In [30]:
df_fetch.drop(columns = ['date'],inplace=True)

/var/folders/v_/6t0wwm_s2nx2wtnfwbgbpgdm0000gn/T/ipykernel_33696/3148099778.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fetch.drop(columns = ['date'],inplace=True)

In [32]:
df_fetch.rename(columns = {'time':'date'},inplace=True)

/var/folders/v_/6t0wwm_s2nx2wtnfwbgbpgdm0000gn/T/ipykernel_33696/930347549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fetch.rename(columns = {'time':'date'},inplace=True)

In [35]:
df_fetch = df_fetch[['id', 'state', 'place', 'latitude', 'longitude','date','temperature_2m_max',
       'temperature_2m_min', 'apparent_temperature_max',
       'apparent_temperature_min', 'precipitation_sum', 'rain_sum',
       'snowfall_sum', 'precipitation_hours', 'sunshine_duration',
       'daylight_duration', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration']]

In [36]:
df_fetch

,id,state,place,latitude,longitude,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,sunshine_duration,daylight_duration,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,et0_fao_evapotranspiration
0,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-05,19.6,8.4,19.1,6.7,0.0,0.0,0.0,0.0,34746.61,37809.66,6.8,21.2,12.52,2.06
1,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-06,19.5,8.1,18.6,6.7,0.0,0.0,0.0,0.0,34845.00,37843.70,8.2,23.4,12.91,2.11
2,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-07,19.5,7.6,18.6,5.8,0.0,0.0,0.0,0.0,34884.99,37879.98,7.1,22.3,13.05,2.15
3,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-08,20.7,8.2,19.6,6.6,0.0,0.0,0.0,0.0,34927.34,37918.44,6.9,21.2,13.09,2.23
4,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-09,21.7,7.9,20.9,6.0,0.0,0.0,0.0,0.0,34971.93,37958.98,7.7,21.6,13.04,2.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8920,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-15,27.0,22.0,32.4,25.5,0.1,0.1,0.0,1.0,35049.68,41398.20,13.9,28.1,18.88,3.67
8921,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-16,27.0,22.2,30.7,25.3,0.2,0.2,0.0,2.0,37780.40,41419.55,16.1,31.0,20.08,4.11
8922,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-17,26.6,21.0,30.0,23.1,1.8,1.8,0.0,3.0,37313.97,41441.52,19.4,42.1,19.47,4.18
8923,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-18,27.0,19.7,29.9,21.3,0.0,0.0,0.0,0.0,38093.04,41464.07,11.5,29.9,20.95,4.32
8924,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-19,27.6,19.8,30.7,21.5,0.0,0.0,0.0,0.0,36353.65,41487.17,14.0,34.6,20.37,4.38

In [38]:
df_fetch.to_sql(
        name="historical_weather_table_predictions",
        con=engine,
        if_exists="append",
        index=False
    )

510

In [40]:
df_fetch

,id,state,place,latitude,longitude,date,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,snowfall_sum,precipitation_hours,sunshine_duration,daylight_duration,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,et0_fao_evapotranspiration
0,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-05,19.6,8.4,19.1,6.7,0.0,0.0,0.0,0.0,34746.61,37809.66,6.8,21.2,12.52,2.06
1,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-06,19.5,8.1,18.6,6.7,0.0,0.0,0.0,0.0,34845.00,37843.70,8.2,23.4,12.91,2.11
2,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-07,19.5,7.6,18.6,5.8,0.0,0.0,0.0,0.0,34884.99,37879.98,7.1,22.3,13.05,2.15
3,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-08,20.7,8.2,19.6,6.6,0.0,0.0,0.0,0.0,34927.34,37918.44,6.9,21.2,13.09,2.23
4,1269655,Arunachal Pradesh,Itanagar,27.08694,93.60987,2026-01-09,21.7,7.9,20.9,6.0,0.0,0.0,0.0,0.0,34971.93,37958.98,7.7,21.6,13.04,2.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
505,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-15,27.0,22.0,32.4,25.5,0.1,0.1,0.0,1.0,35049.68,41398.20,13.9,28.1,18.88,3.67
506,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-16,27.0,22.2,30.7,25.3,0.2,0.2,0.0,2.0,37780.40,41419.55,16.1,31.0,20.08,4.11
507,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-17,26.6,21.0,30.0,23.1,1.8,1.8,0.0,3.0,37313.97,41441.52,19.4,42.1,19.47,4.18
508,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-18,27.0,19.7,29.9,21.3,0.0,0.0,0.0,0.0,38093.04,41464.07,11.5,29.9,20.95,4.32
509,1259425,Puducherry,Puducherry,11.93381,79.82979,2026-01-19,27.6,19.8,30.7,21.5,0.0,0.0,0.0,0.0,36353.65,41487.17,14.0,34.6,20.37,4.38

In [41]:
df_fetch = pd.read_sql_table("historical_aqi_table_predictions", con=engine)

In [43]:
df_fetch = pd.read_sql_table("historical_weather_aqi_table", con=engine)

In [45]:
df_fetch.columns

Index(['state', 'place', 'latitude', 'longitude', 'date', 'temperature_2m_max',
       'temperature_2m_min', 'apparent_temperature_max',
       'apparent_temperature_min', 'precipitation_sum', 'rain_sum',
       'snowfall_sum', 'precipitation_hours', 'sunshine_duration',
       'daylight_duration', 'wind_speed_10m_max', 'wind_gusts_10m_max',
       'shortwave_radiation_sum', 'et0_fao_evapotranspiration', 'pm2_5_mean',
       'ozone_mean', 'ozone_std', 'ozone_min', 'ozone_max', 'dust_mean',
       'uv_index_max', 'uv_index_mean', 'alder_pollen_mean',
       'birch_pollen_mean', 'mugwort_pollen_mean', 'olive_pollen_mean'],
      dtype='object')